/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.senac.br.Telas;

/**
 *
 * @author Red
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonContasPagarDia = new javax.swing.JButton();
        jButtonContasReceberDia = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuNovaConta = new javax.swing.JMenuItem();
        jMenuNovaPessoa = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenuItem();
        jMenuEdit = new javax.swing.JMenu();
        jMenuEditarConta = new javax.swing.JMenuItem();
        jMenuEditarPessoa = new javax.swing.JMenuItem();
        jMenuProcura = new javax.swing.JMenu();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuRelatorioDiario = new javax.swing.JMenuItem();
        jMenuRelatorioSemanal = new javax.swing.JMenuItem();
        jMenuRelatorioMensal = new javax.swing.JMenuItem();
        jMenuUser = new javax.swing.JMenu();
        Cadastro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));

        jButtonContasPagarDia.setText("Resumo Contas a Pagar");
        jButtonContasPagarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContasPagarDiaActionPerformed(evt);
            }
        });

        jButtonContasReceberDia.setText("Resumo Contas a Receber");
        jButtonContasReceberDia.setMaximumSize(new java.awt.Dimension(147, 23));
        jButtonContasReceberDia.setMinimumSize(new java.awt.Dimension(147, 23));
        jButtonContasReceberDia.setPreferredSize(new java.awt.Dimension(147, 23));
        jButtonContasReceberDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContasReceberDiaActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jButtonContasPagarDia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonContasReceberDia, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonContasPagarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonContasReceberDia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonContasPagarDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonContasReceberDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jMenuArquivo.setText("Arquivo");

        jMenuNovaConta.setText("Cadastrar Nova Conta");
        jMenuNovaConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovaContaActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuNovaConta);

        jMenuNovaPessoa.setText("Cadastrar Novo Beneficiário");
        jMenuNovaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovaPessoaActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuNovaPessoa);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuSair);

        jMenuBar1.add(jMenuArquivo);

        jMenuEdit.setText("Editar");

        jMenuEditarConta.setText("Editar Contas");
        jMenuEditarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEditarContaActionPerformed(evt);
            }
        });
        jMenuEdit.add(jMenuEditarConta);

        jMenuEditarPessoa.setText("Editar Beneficiários");
        jMenuEdit.add(jMenuEditarPessoa);

        jMenuBar1.add(jMenuEdit);

        jMenuProcura.setText("Procura");
        jMenuBar1.add(jMenuProcura);

        jMenuRelatorio.setText("Relatórios");

        jMenuRelatorioDiario.setText("Relatório Diário");
        jMenuRelatorio.add(jMenuRelatorioDiario);

        jMenuRelatorioSemanal.setText("Relatório Semanal");
        jMenuRelatorio.add(jMenuRelatorioSemanal);

        jMenuRelatorioMensal.setText("Relatório Mensal");
        jMenuRelatorio.add(jMenuRelatorioMensal);

        jMenuBar1.add(jMenuRelatorio);

        jMenuUser.setText("Usuário");

        Cadastro.setText("Verificar Conta");
        jMenuUser.add(Cadastro);

        jMenuBar1.add(jMenuUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuEditarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEditarContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEditarContaActionPerformed

    private void jMenuNovaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovaPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuNovaPessoaActionPerformed

    private void jMenuNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovaContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuNovaContaActionPerformed

    private void jButtonContasPagarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContasPagarDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContasPagarDiaActionPerformed

    private void jButtonContasReceberDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContasReceberDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContasReceberDiaActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cadastro;
    private javax.swing.JButton jButtonContasPagarDia;
    private javax.swing.JButton jButtonContasReceberDia;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuEditarConta;
    private javax.swing.JMenuItem jMenuEditarPessoa;
    private javax.swing.JMenuItem jMenuNovaConta;
    private javax.swing.JMenuItem jMenuNovaPessoa;
    private javax.swing.JMenu jMenuProcura;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenuItem jMenuRelatorioDiario;
    private javax.swing.JMenuItem jMenuRelatorioMensal;
    private javax.swing.JMenuItem jMenuRelatorioSemanal;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JMenu jMenuUser;
    // End of variables declaration//GEN-END:variables
}
